{% set name = "libassuan" %}
{% set version = "2.5.6" %}
{% set sha256 = "e9fd27218d5394904e4e39788f9b1742711c3e6b41689a31aa3380bd5aa4f426" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://www.gnupg.org/ftp/gcrypt/{{ name }}/{{ name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('libassuan', max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make       # [unix]
    - libtool    # [unix]
    - automake   # [unix]
    - gnuconfig  # [unix]
  host:
    - libgpg-error

test:
  commands:

about:
  home: https://www.gnupg.org/software/libassuan/index.html
  summary: Libassuan is a small library implementing the so-called Assuan protocol.
  license: LGPL-2.1-or-later
  license_family: GPL
  license_file: COPYING.LIB
  description: |
    Libassuan is a small library implementing the so-called Assuan protocol.
    This protocol is used for IPC between most newer GnuPG components.

extra:
  recipe-maintainers:
    - mariusvniekerk
