travis:
  secure:
    BINSTAR_TOKEN: v2ITz3Emdk9R+F6k87gpA3eO9QuFRCDK/+/DMgJWyorQqun+43zoml06dS7C4XWIRu8O0Uy6BUCb8qEJl1UyLBkH1SJDT7IK9xRxgTSSpp1QI13WAgJqBeYZs71Ti9cu3XPI2pyYjVxmlRok+zzLf8g7ygKTukzizLhMSOc/QO0kEJamWFVMdmZBtZD5l0YdMj0BnrqvUjUlpikdwPR1MHSDYhnLc41VLp8syy3vN/1jdJ9+Hugj7EBJEKgDFoGiKIeyFd/EMCBBqqSf+j/6cLTMW/QCwzvf/PM8C8U1d0bWNWTP7oXEQgPmaPcDFBqRLhplg0YhT4OTiml4fst3u0lPXd8Suk6SFGv0q8N4Le8AbLYOE/lJ6PDcpyIV1/7YU3ahoIECaJfldLdiggcpBPzfspCyc/Evv7kZ3Hps39F5+QbB8CtQ9tYE8ManDwBVbDI/McaeaB248vcBSP7SsSyeTN0+qh00+Yc26+ulWfxnASdnw4vZ7IzdHWhCi1a0T71EXdnwFWF/EI7Ab8o1Fc6+QyKLhWVUjfi26OgAhtIausz84S8sc2DXudgIuYvKJW0dnqoF5od3q/WDWxfzEqeNbZhVIbWfODEM6CcByEJe+uezl3FP1fncLkqwsFo5D1mDLBARQ3gLhktmT69dgEcrvH65qGF85NXUJmUK1Is=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
