travis:
  secure:
    BINSTAR_TOKEN: jQvblsumHW6Ofs95WPDtCCclWKpJ8WV+4YRxW3mJ4aIQQPlnImKsiG5ltaXQmENnBCnL641L3O7pHS/ooTC6u4+lvSEoIyD6qGVCXJj4NxCKrwrlqUgMl2U65CRFGxUy3MfV4gdWDf4Nd9OIHp9hys3Y0MiBcs3USqtJx0Yykj1iEF9bmmPcGeFrBcu7InchAF8DS4HCF3OGLUHdOU1o8FJyHBYeWstlD7WqZAnztgU8S0Oh1ipLH1VsjTctnRuhT9NaMp5Xe4MgEgDZpQUn6X3A08lVfur9XfUUrVnXJnsgHjb0o5Oh1gJ2jX9vTlFZarJt5RGi6M16i1h0S7icR98q0FRoyNVjGJJQLoJ5xCz2Vq3mdiu7E44iM10e/9soWMgrn6sGiBtfNV9z/jK4hyGC48XFtprXjtpchL3MdMCFSzpkHBp22Np4o3EZYU/KTDZqYGyXQ8eOoipfobGZbbrSTA383bhk5NSTlmwhvrIiZj8AqtbVocEYsK1t/wNssF49lth0Iq3tAJ+7TEeiGrLcLMakmvP52T0jbOovea1jtPlzjdQH2qDcLALaSsqHuPeDPyW/r9S59Pxdd0dbyR2FEzM9icV7U8JDtehEsRjFCriCQM9kIkdXqYQWIc92vJTYdw17jgJrnpu3jjHE6x8K1/WYy7sABNbOMVx7Ny4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
