appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: rzzlZXmww8S2g7iLPg1zDLXBZ7b9kFRIaQ88nX2moK6cCbRqveIW/GB8hQBfiQqDaZmjD6frKqV0wqG0fipTwatVt7W23gydB3SVskVdXtD/rUrp7kqGs/a7hLxErjPZPZgVmtnSQ+gaDotuzxaLhsL0tJxgVAQLGweO9y3R80UKRpv58EHXnV3AZKhCxTbIQmKAYoSt4DaV7cgibM9Z9ObwwNiXvJbEUIjFkrnSfGM7LKrcN19oRgHoUZyVwpWa7amuV07hVRPH5uMtIFRAL5gSKBwR/j9wSBYdv3XgTzaWCfSXq38NjG6VKvF/dfT/S1mmzzEDxg+HGiXvRBmrrBcx2kuWBjnXjOr4voGj/vnJYRa5FQ8IS/voaAHUZ3RkbPopxySeV0rwZgGzWE8VGIkfLSbr2Hp2EmWt9TvePH3Pzv7dbGtqvYWqgzVRSpjLfIlrqPImhDJxGHmlR0xfYEnPFfSgL5zueis5eZ9XVOn0AUJwNqZy6tqZBV7yzJhf7uYzxph3EW/lOnCrCwNGWhWxSOqUdg8YOrR8nRjk1oolZkTiXrPLUCYgalbjmFrVpqMGi362vrxgX2W7oloiS/XYWeVIsp09kgrRHzSwV0jECRoJ+6jRoVfz0q6vWazKKKOGcKb8VuP2w8Xk4kUDa0xCng28rcdunNqK978DRR4=}
conda_forge_output_validation: true
